{
           "中文姓": "$Var{surname}=$Func{strSurname()}",
           "中文名": "$Var{firstname}=$Func{strFirstName()}",
           "中文姓名": "$Var{surname}$Var{firstname}",
           "英文姓名": "$Func{strEnglistNameMan()}",
           "別名": "$Func{strName()}",
           "性別": "$Var{s}=$Dic{sex}",
           "婚姻狀態": "$Dic{marital}",
           "子女數": "$Dic{child}",
           "服務機構": "$Dic{job}",
           "最高學歷": "$Dic{education}",
           "年收入": "$Dic{salary}",
           "資金來源": "$Dic{source}",
           "E-mail": "$Func{strEmail()}",
           "任職公司": "$Func{strCompany()}",
           "公司電話": "$Func{strCompanyPhone()}",
           "國籍": "$Dic{country}",
           "語系": "$Func{strLocale()}",
           "出生地": "$Var{town}=$Dic{town}",
           "出生日期": "$Func{strBirthday()}",
           "戶籍地址": "$Func{strStreet()}",
           "帳戶用途": "$Dic{usage}",
           "戶名": "$Var{surname}$Var{firstname}",
           "手機號碼":  "$Func{strMobilePhone(0)}",
           "抵押貸款額度": "$Dic{mortgage}",
           "是否申請金融卡非約定轉帳": "$Dic{transfer}",
           "身分證發證地點": "$Var{town}",
           "統一編號": "$Func{strUniform()}",
           "uid" : "$Func{strUUID(1)}",
           "adid" : "$Func{strUUID(0)}",
           "num" : "$Func{strMobilePhone(1)}",
           "region" : "$Func{strRegion(0)}",
           "city" : "$Func{strTaiwanCity()}",
           "os" : "$Func{strOS(0)}",
           "os_version" : "$Dic{android_version}",
           "subscript_status" : "$Dic{subscript_status}",
           "manufaturer" : "$Dic{manufaturer}",
           "model" : "$Dic{model}",
           "language" : "$Func{strLanguage(0)}",
           "login_status" : "$Func{intLoginStatus()}"
}
 
